language: php
php:
  - '5.6'

sudo: required

notifications:
  slack: toolwatchapp:AfvHCPE9Em1MY3j04gdlqbYe
  email: false

before_script:
  - pear config-set preferred_state beta
  - yes '' | pecl install apcu
  - composer install

script:
  - cd application/tests/ && phpunit --coverage-text
  - php coverage-checker.php build/logs/clover.xml 100
