language: php
php:
  - '5.6'

notifications:
  slack: toolwatchapp:AfvHCPE9Em1MY3j04gdlqbYe
  email: false

before_script:
    - echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - echo "apc.enable = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - echo "apc.enable_cli = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - composer install

script:
  - cd application/tests/ && phpunit --coverage-text
  - php coverage-checker.php build/logs/clover.xml 100
